import React from "react";
import { BottomTableToolbar } from "./BottomTableToolBar";
import { DynamicTable } from "@/shared/components/Table";
import { ColumnConfig } from "@/shared/components/Table";

export default function TableDataSection() {
  const mockData = [
    {
      status: "Completed",
      orderId: "#ORD-88293",
      equipment: "Mud-pump",
      capacity: "10 tons",
      bookingDate: "12/03/2026",
      startsOn: "12/03/2026",
      endOn: "14/03/2026",
      extended: "14/03/2026 (12:30)",
      firstLocation: "HPM HQ, Banga...",
      secondLocation: "-",
      customerId: "V-OD-12345",
      vendorId: "V-OD-12345",
      operatorId: "op-12345X-S",
      ratings: "5.0",
      payment: "COD",
      coupon: "FIRSTBUY50",
    },
    {
      status: "Started",
      orderId: "#ORD-88294",
      equipment: "Truck",
      capacity: "20 tons",
      bookingDate: "12/03/2026",
      startsOn: "-",
      endOn: "-",
      extended: "-",
      firstLocation: "HPM HQ, Banga...",
      secondLocation: "WXP HQ, Ban...",
      customerId: "V-OD-12346",
      vendorId: "V-OD-12346",
      operatorId: "op-12346X-S",
      ratings: "-",
      payment: "Online",
      coupon: "-",
    },
    {
      status: "Arrived",
      orderId: "#ORD-88295",
      equipment: "Truck",
      capacity: "20 tons",
      bookingDate: "12/03/2026",
      startsOn: "12/03/2026",
      endOn: "14/03/2026",
      extended: "-",
      firstLocation: "HPM HQ, Banga...",
      secondLocation: "WXP HQ, Ban...",
      customerId: "V-OD-12347",
      vendorId: "V-OD-12347",
      operatorId: "op-12347X-S",
      ratings: "-",
      payment: "Online",
      coupon: "-",
    },
    {
      status: "Completed",
      orderId: "#ORD-88296",
      equipment: "Mud-pump",
      capacity: "20 tons",
      bookingDate: "12/03/2026",
      startsOn: "12/03/2026",
      endOn: "14/03/2026",
      extended: "Declined",
      firstLocation: "HPM HQ, Banga...",
      secondLocation: "-",
      customerId: "V-OD-12348",
      vendorId: "V-OD-12348",
      operatorId: "op-12348X-S",
      ratings: "-",
      payment: "Online",
      coupon: "-",
    },
    {
      status: "Completed",
      orderId: "#ORD-88297",
      equipment: "Truck",
      capacity: "20 tons",
      bookingDate: "12/03/2026",
      startsOn: "12/03/2026",
      endOn: "14/03/2026",
      extended: "-",
      firstLocation: "HPM HQ, Banga...",
      secondLocation: "WXP HQ, Ban...",
      customerId: "V-OD-12349",
      vendorId: "V-OD-12349",
      operatorId: "op-12349X-S",
      ratings: "-",
      payment: "Online",
      coupon: "-",
    },
    {
      status: "Completed",
      orderId: "#ORD-88298",
      equipment: "Truck",
      capacity: "20 tons",
      bookingDate: "12/03/2026",
      startsOn: "12/03/2026",
      endOn: "14/03/2026",
      extended: "-",
      firstLocation: "HPM HQ, Banga...",
      secondLocation: "WXP HQ, Ban...",
      customerId: "V-OD-12350",
      vendorId: "V-OD-12350",
      operatorId: "op-12350X-S",
      ratings: "-",
      payment: "Online",
      coupon: "-",
    },
    {
      status: "Extended",
      orderId: "#ORD-88299",
      equipment: "Truck",
      capacity: "20 tons",
      bookingDate: "12/03/2026",
      startsOn: "12/03/2026",
      endOn: "14/03/2026",
      extended: "14/03/2026 (12:30)",
      firstLocation: "HPM HQ, Banga...",
      secondLocation: "WXP HQ, Ban...",
      customerId: "V-OD-12351",
      vendorId: "V-OD-12351",
      operatorId: "op-12351X-S",
      ratings: "-",
      payment: "Online",
      coupon: "-",
    },
  ];

  const columns: ColumnConfig<any>[] = [
    { header: "Status", key: "status", width: 120, align: "center" },
    { header: "Order Id", key: "orderId", width: 140, align: "center" },
    { header: "Equipment", key: "equipment", width: 150, align: "center" },
    { header: "Capacity", key: "capacity", width: 100, align: "center" },
    { header: "Booking Date", key: "bookingDate", width: 140, align: "center" },
    { header: "Starts On", key: "startsOn", width: 140, align: "center" },
    { header: "End On", key: "endOn", width: 140, align: "center" },
    { header: "Extended", key: "extended", width: 160, align: "center" },
    {
      header: "1st Location",
      key: "firstLocation",
      width: 180,
      align: "center",
    },
    {
      header: "2nd Location",
      key: "secondLocation",
      width: 180,
      align: "center",
    },
    { header: "Customer Id", key: "customerId", width: 140, align: "center" },
    { header: "Vendor Id", key: "vendorId", width: 140, align: "center" },
    { header: "Operator Id", key: "operatorId", width: 140, align: "center" },
    { header: "Ratings", key: "ratings", width: 80, align: "center" },
    { header: "Payment", key: "payment", width: 100, align: "center" },
    { header: "Coupon", key: "coupon", width: 120, align: "center" },
    { header: "Booking Details", key: "details", width: 120, align: "center" }, // Maps to "View Full"
    { header: "Manage", key: "manage", width: 100, align: "center" }, // Maps to "Edit"
  ];
  return (
    <div className="flex flex-col gap-[12px]">
      <BottomTableToolbar></BottomTableToolbar>
      <DynamicTable
        columns={columns}
        data={mockData}
        maxHeight={401} // Adjust as needed for your design
      />
    </div>
  );
}
