// 1. Export the table data
// export const mockInventoryTableData = [
//   { name: "Truck", capacity: "10-12 ft", brand: "-", analysis: "High Value", quantity: "20.7k", hasQuantityAlert: false, cost: "9.8k/km", fuel: "300/km", operatorFee: "200/hr", vendors: "12", searchRate: "-" },
//   { name: "Bulldozer", capacity: "Truck Dozer", brand: "Volvo", analysis: "Medium Value", quantity: "12.8k", hasQuantityAlert: false, cost: "2.6k/8hr", fuel: "250/hr", operatorFee: "300/hr", vendors: "32", searchRate: "1.2%" },

// ];

import { InventoryItem } from "../types"; // 1. Add this import


export const mockInventoryTableData : InventoryItem[] =[
  {
    name: "Truck",
    capacity: "10-12 ft",
    brand: "-",
    analysis: "High Value",
    quantity: "20.7k",
    hasQuantityAlert: false,
    cost: "9.8k/km",
    fuel: "300/km",
    operatorFee: "200/hr",
    vendors: "12",
    searchRate: "-",
  },
  {
    name: "Bulldozer",
    capacity: "Truck Dozer",
    brand: "Volvo",
    analysis: "Medium Value",
    quantity: "12.8k",
    hasQuantityAlert: false,
    cost: "2.6k/8hr",
    fuel: "250/hr",
    operatorFee: "300/hr",
    vendors: "32",
    searchRate: "1.2%",
  },
  {
    name: "Borewell",
    capacity: "Identifying",
    brand: "Hitachi",
    analysis: "Low Value",
    quantity: "23.9k",
    hasQuantityAlert: false,
    cost: "1.3k/km",
    fuel: "-",
    operatorFee: "100/hr",
    vendors: "1",
    searchRate: "3.7%",
  },
  {
    name: "Tipper",
    capacity: "Conversion",
    brand: "Volvo",
    analysis: "Low Value",
    quantity: "11",
    hasQuantityAlert: true,
    cost: "7.7k/km",
    fuel: "300/km",
    operatorFee: "100/hr",
    vendors: "2",
    searchRate: "1.2%",
  },
  {
    name: "Borewell",
    capacity: "Identifying",
    brand: "Volvo",
    analysis: "Medium Value",
    quantity: "12.8k",
    hasQuantityAlert: false,
    cost: "1k/km",
    fuel: "-",
    operatorFee: "100/hr",
    vendors: "5",
    searchRate: "3.7%",
  },
  {
    name: "Borewell",
    capacity: "Identifying",
    brand: "-",
    analysis: "Medium Value",
    quantity: "12",
    hasQuantityAlert: true,
    cost: "2k/8hr",
    fuel: "-",
    operatorFee: "100/hr",
    vendors: "12",
    searchRate: "-",
  },
  {
    name: "Borewell",
    capacity: "Identifying",
    brand: "Hitachi",
    analysis: "Low Value",
    quantity: "23.9k",
    hasQuantityAlert: false,
    cost: "8k/8hr",
    fuel: "-",
    operatorFee: "100/hr",
    vendors: "43",
    searchRate: "1.2%",
  },
  {
    name: "Truck",
    capacity: "Drilling",
    brand: "Hitachi",
    analysis: "Low Value",
    quantity: "12.8k",
    hasQuantityAlert: false,
    cost: "8k/8hr",
    fuel: "300/km",
    operatorFee: "100/hr",
    vendors: "21",
    searchRate: "1.2%",
  },
  {
    name: "Borewell",
    capacity: "Identifying",
    brand: "Volvo",
    analysis: "Low Value",
    quantity: "23.9k",
    hasQuantityAlert: false,
    cost: "8k/km",
    fuel: "-",
    operatorFee: "300/hr",
    vendors: "32",
    searchRate: "3.7%",
  },
  {
    name: "Truck",
    capacity: "Drilling",
    brand: "-", // Blank in image
    analysis: "Low Value",
    quantity: "12.8k",
    hasQuantityAlert: false,
    cost: "8k/8hr",
    fuel: "300/km",
    operatorFee: "300/hr",
    vendors: "12",
    searchRate: "-",
  },
  {
    name: "Borewell",
    capacity: "Identifying",
    brand: "Hitachi",
    analysis: "Low Value",
    quantity: "12.8k",
    hasQuantityAlert: false,
    cost: "8k/8hr",
    fuel: "-",
    operatorFee: "300/hr",
    vendors: "6",
    searchRate: "1.2%",
  },
  {
    name: "Borewell",
    capacity: "Drilling",
    brand: "Hitachi",
    analysis: "Low Value",
    quantity: "23.9k",
    hasQuantityAlert: false,
    cost: "8k/km",
    fuel: "300/hr",
    operatorFee: "300/hr",
    vendors: "9",
    searchRate: "1.2%",
  },
  {
    name: "Borewell",
    capacity: "Identifying",
    brand: "Volvo",
    analysis: "Low Value",
    quantity: "12.8k",
    hasQuantityAlert: false,
    cost: "8k/km",
    fuel: "-",
    operatorFee: "300/hr",
    vendors: "10",
    searchRate: "3.7%",
  },
  {
    name: "Borewell",
    capacity: "Drilling",
    brand: "Hitachi",
    analysis: "Low Value",
    quantity: "100",
    hasQuantityAlert: true,
    cost: "8k/8hr",
    fuel: "-",
    operatorFee: "300/hr",
    vendors: "1",
    searchRate: "3.7%",
  },
];

// 2. Export the top Info Card stats
export const mockInventoryCards = [
  {
    title: "Total Equipment",
    Stats: "12,091",
    percentage: -20.89,
    information: "Total number of equipment currently in the inventory.",
  },
  {
    title: "To be assigned",
    Stats: "91",
    percentage: -20.89,
    information: "Equipment available and waiting to be assigned to a project.",
  },
  {
    title: "Booked",
    Stats: "123",
    percentage: -20.89,
    information: "Equipment currently booked for upcoming rentals.",
  },
  {
    title: "Active",
    Stats: "232",
    percentage: -20.89,
    information: "Equipment currently active and deployed in the field.",
  },
  {
    title: "Equipment Utilization",
    Stats: "19.2%",
    percentage: -20.89,
    information: "Percentage of total equipment currently in use.",
  },
];
